### ISSUE TITLE
Implement wdyt command and remove the current output

### ISSUE THREAD

**Issue by PragTob** [PragTob/rubykon#8]
The `wdyt` command should print out what rubykon thought when playing the last move. E.g. the most popular moves it chose.

At the same time also remove the current output.

**Comment by ujh** [comment]
If you were to implement GTP first you could even put this data on top of the current position with the [GoGui analyze](http://gogui.sourceforge.net/doc/analyze.html) command. 

I'll shut up about GTP now. :grin:

**Comment by PragTob** [comment]
:D Yeah GTP is definitely on the horizone, but it seemed more complicated than building a nice little CLI that people can `gem install rubykon` and play with it here for my rubyconf talk (in an hour or so!) - it is live btw :D 

and this is fixed :D

**Comment by ujh** [comment]
Talk driven development is of course a good excuse. ;)

**Comment by PragTob** [comment]
I heard @jasonrclark say this before. There is still this property based testing library that actually gives a nice interface for side effects et. al. in ruby that I'd build if the talk would just get accepted :P

**Comment by ujh** [comment]
😂

**Comment by jasonrclark** [comment]
:microphone: :car: :computer: :sparkling_heart:
